# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20180927_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
